### ISSUE TITLE
No options in User CP

### ISSUE THREAD

**Issue by marcandrews** [Shade-/MyGoogle--Connect#11]
The options for Google Plus integration (like those for MyFacebook Connect) are missing from the User CP. Any ideas on how to get the Google Plus integration User CP options to show so that registered forum users can link their forum account with Google Plus?

**Comment by marcandrews** [comment]
The fix  for MyTwitter Connect ([found here](http://community.mybb.com/thread-138202-post-1078706.html#pid1078706)) also works for MyGoogle+ Connect.

Find
```php
if ($settings['mygpconnect_enabled']) {
```

Replace with
```php
if ($mybb->settings['mygpconnect_enabled']) {
```

**Comment by Shade-** [comment]
Darn. I was quite sure to have updated the plugin a while ago, this issue was addressed back in 2014 for MFC. It's fairly odd, I will check for sure.

**Comment by Shade-** [comment]
The lastest versions do include this fix already. You are using an outdated version.

**Comment by marcandrews** [comment]
Then the version posted on MyBB Extend is outdated.

**Comment by Shade-** [comment]
As far as I know, the version on the new Mods Site is exactly the same as this on GitHub. Maybe you have downloaded it from the old site?

**Comment by marcandrews** [comment]
Tt is fixed in the [master branch](https://github.com/Shade-/MyGoogle--Connect/blob/master/inc/plugins/mygpconnect.php#L266), but [2.0.1](https://github.com/Shade-/MyGoogle--Connect/blob/2.0.1/inc/plugins/mygpconnect.php#L264) **does not** have this fix included.

**Comment by Shade-** [comment]
That's because 2.0.1 is for MyBB 1.6 only. 2.1, which is the one uploaded in the new Mods Site, is compatible with the new versions of MyBB (and with 1.6 as well) and contains the patch.

**Comment by marcandrews** [comment]
I just downloaded it again from [here](http://community.mybb.com/mods.php?action=download&pid=96&bid=137) and this fix is **not included**.

**Comment by Shade-** [comment]
Odd. I will surely check that zip. The strange thing is that it has been downloaded thousands times and still I haven't received any bug report in 11 months.

**Comment by marcandrews** [comment]
OT: I've noticed that a lot of MyBB admins quickly give up on plugins if they don't work right out of the box, and don't even bother posting about them or inquiring with the dev.

**Comment by Shade-** [comment]
Yeah I know. The thing is, people just think they are installing an official software but that's not the case for third party add ons. Furthermore, integration tweaks like my own plugins are even more likely to fail because of the extremely wide range of variables which external sites put in the game. I always try to seek perfection but that's way too hard to obtain. The fact that I have such few bug reports and still as many downloads really makes me proud of my work, but people should acknowledge that these softwares are written by students or freelancers in their free time, especially when they are free, and they should expect some bugs.

**Comment by Shade-** [comment]
Ok so apparently the plugin has stopped working due to the API being out of date. I have written down an early updated version which uses the new functions introduced in a newly released API version and I will update the plugin as soon as possible.

**Comment by marcandrews** [comment]
Your plugin still works for me

**Comment by Shade-** [comment]
Whatever. I have created the development branch with a fix also for #12.

**Comment by marcandrews** [comment]
> Whatever.

See for yourself on my [MyBB Dev Forum](https://gamingchapter.org/dev).

**Comment by Shade-** [comment]
Even if it works, it didn't on my server. The new version does work and I will release it in a hour.

**Comment by Shade-** [comment]
Released. An announcement will be made with instructions on how to update from older versions.
