### ISSUE TITLE
Text missing

### ISSUE THREAD

**Issue by marcandrews** [Shade-/MyGoogle--Connect#12]
There are a few instances where the language bits are incorrectly referenced, causing text to be missing in, for example, the User CP. These are instances where ```$lang->setting_mygpconnect_``` should actually be ```$lang->mygpconnect_settings_```

Two examples occur [here](https://github.com/Shade-/MyGoogle--Connect/blob/master/inc/plugins/mygpconnect.php#L487-L488) in the master branch as of this date. There may be other instances.

**Comment by Shade-** [comment]
Fixed in #13.
