### ISSUE TITLE
installation instruction

### ISSUE THREAD

**Issue by oneala** [Shade-/MyGoogle--Connect#17]
Hi,

I just checked and there is no installation instructions for this, please help :)

thanks!

**Comment by ErikThiart** [comment]
I am giving up. No installation instructions, no setup via the developer console guide which in itself is a mess.

I managed to het the API key and Oauth ID and Secret

However your plugin does not want to work it kicks out a 500 error after the redirect from google.

**Comment by Shade-** [comment]
Installation instructions are in the wiki https://github.com/Shade-/MyGoogle--Connect/wiki/How-to-install

Sorry to hear that.

**Comment by ErikThiart** [comment]
Silly us. Was just about to post this. Github's new layout confused me a bit. On it now!

**Comment by ErikThiart** [comment]
I need some help here -> What do you add here since the defaults does not work.

After registration usergroup
Select the after-registration usergroup. The user will be inserted directly into this usergroup upon registering. Also, if an existing user links his account to Google+, this usergroup will be added to his additional groups list.

1

**Comment by ErikThiart** [comment]
![2016-06-10_12-59-55](https://cloud.githubusercontent.com/assets/9626641/15962442/58df759e-2f0b-11e6-8550-35fbc77a3fd2.jpg)

This is what happens after a user press login

**Comment by oneala** [comment]
it worked perfect for me without any error, have you followed each step of installation tutorial ?

**Comment by ErikThiart** [comment]
Yea, followed it to the brim. I promise. I made sure.

**Comment by ErikThiart** [comment]
where did you download the plugin from? Here or mybb?

**Comment by ErikThiart** [comment]
Can I download this:

https://github.com/Shade-/MyGoogle--Connect/releases

And upload it to my FTP

I downloaded the pugin from mybb

**Comment by ErikThiart** [comment]
Loaded that one. All works like a charm now!

**Comment by Shade-** [comment]
Yeah sorry, might be outdated.
