### ISSUE TITLE
Can't Login

### ISSUE THREAD

**Issue by 930C** [Shade-/MyGoogle--Connect#18]
After clicking on the "Google+ integration" button, i can choose between my google accounts 
![chrome_2016-10-20_20-53-35](https://cloud.githubusercontent.com/assets/12743335/19573861/2dc07786-9708-11e6-9868-28975d2aa9a7.png)
, but after login in, it shows this message 
![chrome_2016-10-20_21-01-33](https://cloud.githubusercontent.com/assets/12743335/19573915/696515d0-9708-11e6-9ba6-db153acabd8e.png)... I've done every step on the Installation Instruction (https://github.com/Shade-/MyGoogle--Connect/wiki/How-to-install).
I am using apache 2 and running my Server on the OS Linux (Debian 8 Jessie)

PS: It says 

> A bug report has been generated and it's available in the administration panel.

But i didn't find any bug reports and I want to know where the report should be shown...

Greetings, Kradosser.

**Comment by 930C** [comment]
Ok, it says it's something wrong in /var/www/mygpconnect/src/Http/REST.php LINE 110 CODE 403

**Comment by pielat** [comment]
Hello @kradosser 
Did you find any solution for that? I've the same problem :/

**Comment by Shade-** [comment]
Please open a new thread on MyBBoost to receive support.
