### ISSUE TITLE
Organization has G+ Disabled

### ISSUE THREAD

**Issue by Blacnova** [Shade-/MyGoogle--Connect#19]
Hey, so I am currently trying to make a forum for my organization (I am not an admin), and the organization uses Google accounts with our own domain. The administrator has Google plus disabled and so we are unable to login with the accounts as it tells us to Enter a Username (even after we enter one it still tells us to enter one. Is there anyway I can unlink this plugin from G+ and make it solely reliant on Google user data itself?

Thanks for reading.

**Comment by Shade-** [comment]
MyGoogle+ Connect relies on Google+. If you don't have it enabled, there's no way you can use it to log in to your board.

**Comment by Blacnova** [comment]
Darn, I saw another person doing it without G+ so I thought it might be possible. Thanks anyways for a nice plugin.
